image: registry.gitlab.com/addictedcoders/tdb-service

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy

#test:
#  stage: test
#  script: ./gradlew test
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#    paths:
#      - .gradle

build:
  stage: build
  script: ./gradlew build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
  artifacts:
    paths:
      - artifacts

deploy_staging:
  stage: deploy
  script:
    - heroku deploy:jar build/libs/tdb-service-0.0.1.jar --app tdb-service
#    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  environment:
    name: tdb-service-staging
    url: https://tdb-service.herokuapp.com/api
  only:
  - master