image: registry.gitlab.com/addictedcoders/tdb-service

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy

build:
  stage: build
  script: ./gradlew build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
  artifacts:
    paths:
      - artifacts

deploy_staging:
  stage: deploy
  dependencies:
    - build
  script:
    - echo $pwd
    - ls
    - heroku deploy:jar artifacts/libs/tdb-service-0.0.1.jar --app tdb-service
  environment:
    name: tdb-service-staging
    url: https://tdb-service.herokuapp.com/api
  only:
  - master