image: openjdk:8u131-jdk-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - test
  - build
  - deploy

test:
  stage: test 
  script: ./gradlew test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle

build:
  stage: build
  script: /gradlew build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
  artifacts:
    paths:
      - artifacts

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: tdb-service-staging
    url: https://tdb-service.herokuapp.com/
  only:
  - master