swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Test Dashboard"
  contact:
    email: "dasnervtdoch@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
paths:
  /upload-junit4-xml:
      post:
        operationId: uploadJUnit4Xml
        consumes:
          - "multipart/form-data"
        parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: The file to upload.
        - in: formData
          name: externalProjectId
          type: string
          required: true
          description: Parent project.
        - in: formData
          name: externalTestRunId
          type: string
          required: true
          description: Relate single test execution to a test run.
        tags:
          - Upload
        responses:
          200:
            description: Successful upload
            schema:
              $ref: '#/definitions/TestSuiteDTO'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/ErrorDTO'
  /account/{accountId}:
    get:
      summary: Account
      description: Get the account specified by the given accountId.
      operationId: getAccount
      parameters:
        - name: accountId
          in: path
          description: Id of requested account.
          required: true
          type: integer
          format: int64
      tags:
        - Account
      responses:
        200:
          description: The requested account
          schema:
            $ref: '#/definitions/AccountDTO'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorDTO'
  /account/{accountId}/projects:
    get:
      summary: Account Projects
      description: Get all projects for the account specified by the given accountId.
      operationId: getProjects
      parameters:
        - name: accountId
          in: path
          description: Id of the owning account.
          required: true
          type: integer
          format: int64
      tags:
        - Account
      responses:
        200:
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/ProjectDTO'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorDTO'
  /project/{projectId}:
    get:
      summary: Get a single project
      description: Get the project specified by the given projectId.
      operationId: getProject
      parameters:
        - name: projectId
          in: path
          description: Id of requested project.
          required: true
          type: integer
          format: int64
      tags:
        - Project
      responses:
        200:
          description: The requested project
          schema:
            $ref: '#/definitions/ProjectDTO'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorDTO'
  /project/{projectId}/testruns:
    get:
      tags:
        - Project
      summary: Get all the tests runs for a single project.
      description: Get all the tests runs for the project specified by the given projectId.
      operationId: getProjectTestRuns
      parameters:
        - name: projectId
          in: path
          description: Id of requested project.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: The requested project
          schema:
            type: array
            items:
              $ref: '#/definitions/TestRunDTO'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorDTO'
securityDefinitions:
  test_dashbard_auth:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  AccountDTO:
    type: object
    required:
    - accountName
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      projects:
        type: array
        items:
          $ref: '#/definitions/ProjectDTO'
  ProjectDTO:
    type: object
    required:
    - name
    - accountId
    properties:
      id:
        type: integer
        format: int64
      externalId:
        type: string
      name:
        type: string
      accountId:
        type: integer
        format: int64
      testRuns:
        type: array
        items:
          $ref: '#/definitions/TestRunDTO'
  ErrorDTO:
    type: object
    required:
    - name
    - message
    - code
    properties:
      name:
        type: string
      message:
        type: string
      code:
        type: string
  ResponseDTO:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
      code:
        type: string
  UploadRequestDTO:
      type: object
      required:
      - projectId
      - externalTestRunId
      properties:
        projectId:
          type: integer
          format: int64
        externalTestRunId:
          type: integer
          format: int64
  TestRunDTO:
    type: object
    required:
    - projectId
    properties:
      id:
        type: integer
        format: int64
      externalId:
        type: string
      name:
        type: string
      projectId:
        type: integer
        format: int64
      testSuites:
        type: array
        items:
          $ref: '#/definitions/TestSuiteDTO'
  TestSuiteDTO:
    type: object
    required:
    - testRunId
    - packageName
    - name
    properties:
      id:
        type: integer
        format: int64
      testRunId:
        type: integer
        format: int64
      packageName:
        type: string
      name:
        type: string
      testCases:
        type: array
        items:
          $ref: '#/definitions/TestCaseDTO'
  TestCaseDTO:
    type: object
    required:
    - testSuiteId
    - startDate
    - endDate
    - skipped
    - failed
    properties:
      id:
        type: integer
        format: int64
      testSuiteId:
        type: integer
        format: int64
      name:
        type: string
      startDate:
        type: string
        format: date-time
      endDate:
        type: string
        format: date-time
      skipped:
        type: boolean
      failed:
        type: boolean
      message:
        type: string