###
#   Database Settings
###
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true